# Generated by Django 2.2.4 on 2019-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='code')),
            ],
            options={
                'verbose_name': 'device',
                'unique_together': {('name', 'code')},
            },
        ),
    ]
