# Generated by Django 2.2.4 on 2019-08-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('nit', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='nit')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_city_set', to='city.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'company',
            },
        ),
    ]
